// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace HealthKitSample
{
	public partial class StepCountTableViewController
	{
		public StepCountTableViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			//This table view allows us to add / remove items. Woo!
			this.NavigationItem.RightBarButtonItems= new UIBarButtonItem[]{
				new UIBarButtonItem(UIBarButtonSystemItem.Add, new EventHandler((o,e) => {
					AddStepCountEntry(1598);
				})), 
				this.EditButtonItem};

			// Perform any additional setup after loading the view, typically from a nib.

			//This ensures we are bound to a dispatcher so we can retrieve our data.
			Bind();

		}

		public override void ViewDidUnload ()
		{
			base.ViewDidUnload ();

			Unbind ();
		}
	}
}
